### ISSUE TITLE
ValueError: File ./Mus_musculus.GRCm39.103.gtf must have the 9 mandatory .gtf columns.

### ISSUE THREAD

**Issue by ogola89** [jipingw/DegNorm#1]
Hi there,

I am trying to use this package, but it seems the gtf files are not being recognised as correct gtf files. I have tried to obtain the latest mouse gtf files, which I have used to index and align using STAR with no problem. However, it seems to be giving me this issue and I'm not sure why. I have tried different versions of the gencode and the ensembl gtf files available for mus musculus but to no avail. 

Here is the entire traceback:
```
DegNorm (03/22/2021 04:23:24) ---- DegNorm output directory -- degnorm_output/degnorm_03222021_162324
DegNorm (03/22/2021 04:23:24) ---- SAMPLE mouse_10_sorted -- sample contains single-end reads
DegNorm (03/22/2021 04:23:24) ---- SAMPLE mouse_11_sorted -- sample contains single-end reads
DegNorm (03/22/2021 04:23:24) ---- SAMPLE mouse_1_sorted -- sample contains single-end reads
DegNorm (03/22/2021 04:23:24) ---- SAMPLE mouse_2_sorted -- sample contains single-end reads
DegNorm (03/22/2021 04:23:24) ---- SAMPLE mouse_5_sorted -- sample contains single-end reads
DegNorm (03/22/2021 04:23:24) ---- SAMPLE mouse_6_sorted -- sample contains single-end reads
DegNorm (03/22/2021 04:23:24) ---- SAMPLE mouse_8_sorted -- sample contains single-end reads
DegNorm (03/22/2021 04:23:24) ---- SAMPLE mouse_9_sorted -- sample contains single-end reads
DegNorm (03/22/2021 04:23:24) ---- Begin genome annotation file processing...
DegNorm (03/22/2021 04:23:24) ---- Loading genome annotation file ./Mus_musculus.GRCm39.103.gtf...
Traceback (most recent call last):
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/DegNorm-0.1.4-py3.6.egg/degnorm/loaders.py", line 134, in get_data
    , low_memory=False)
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/pandas/io/parsers.py", line 1902, in __init__
    _validate_usecols_names(usecols, self.names)
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/pandas/io/parsers.py", line 1237, in _validate_usecols_names
    "columns expected but not found: {missing}".format(missing=missing)
ValueError: Usecols do not match columns, columns expected but not found: [1, 2, 3, 4, 5, 6, 7, 8]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/mdp18too/degnorm/bin/degnorm", line 33, in <module>
    sys.exit(load_entry_point('DegNorm==0.1.4', 'console_scripts', 'degnorm')())
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/DegNorm-0.1.4-py3.6.egg/degnorm/__main__.py", line 84, in main
    exon_df = gap.run()
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/DegNorm-0.1.4-py3.6.egg/degnorm/gene_processing.py", line 107, in run
    exon_df = self.load()
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/DegNorm-0.1.4-py3.6.egg/degnorm/gene_processing.py", line 35, in load
    exon_df = self.loader.get_data()
  File "/data/mdp18too/degnorm/lib/python3.6/site-packages/DegNorm-0.1.4-py3.6.egg/degnorm/loaders.py", line 136, in get_data
    raise ValueError('File {0} must have the 9 mandatory .gtf columns.\nRead more at https://useast.ensembl.org/info/website/upload/gff.html'.format(self.filename))
ValueError: File ./Mus_musculus.GRCm39.103.gtf must have the 9 mandatory .gtf columns.
Read more at https://useast.ensembl.org/info/website/upload/gff.html
```

This is a representative traceback when using a number of different gtf files, and these are the gtf files I have tried:
Mus_musculus.GRCm39.103.gtf.gz   from http://ftp.ensembl.org/pub/release-103/gtf/mus_musculus/
gencode.vM26.chr_patch_hapl_scaff.annotation.gtf.gz  and  gencode.vM26.annotation.gtf from https://www.gencodegenes.org/mouse/

All are GRCm39 as that's what I used with STAR.

Please let me know of a way to resolve this issue,.

Thanks.

**Comment by ogola89** [comment]
Solved this by deleting the comments in the first 5 lines of the gtf file
